options:
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-compute"
    namespace: "com.azure.resourcemanager.compute"
    service-name: "Compute" # human-readable service name, whitespace allowed
    flavor: azure
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/compute"
    emitter-output-dir: "{output-dir}/{service-dir}/armcompute"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armcompute"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-ts":
    service-dir: "sdk/compute"
    experimental-extensible-enums: true
    emitter-output-dir: "{output-dir}/{service-dir}/arm-compute"
    flavor: azure
    package-details:
      name: "@azure/arm-compute"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
